# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- tvlk/4.0.11.tvlk

pr:
- tvlk/4.0.11.tvlk

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  projects: 'src/Npgsql/**/*.csproj'

steps:
- task: DotNetCoreInstaller@0
  displayName: Install .NET Core 2.2
  inputs:
    packageType: 'sdk'
    version: '2.2.102'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack into NuGet Package
  inputs:
    command: 'pack'
    configuration: $(buildConfiguration)
    projects: '$(projects)'

- task: DotNetCoreCLI@2
  condition: eq(variables['Build.SourceBranchName'], 'master')
  displayName: Publish to NuGet Feed
  inputs:
    command: 'push'
    feedPublish: 'tvlk-ecb'
    projects: '$(projects)'
